[daemons.tailscaled]
# add for userspace networking:  --tun=userspace-networking --socks5-server=localhost:1055
run = "tailscaled"
ready_cmd = "curl --unix-socket /run/tailscale/tailscaled.sock http://local-tailscaled.sock/"
user = "root"
boot_start = true
